/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_liujs_com_testndk_MainActivity */

#ifndef _Included_android_liujs_com_testndk_MainActivity
#define _Included_android_liujs_com_testndk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_liujs_com_testndk_MainActivity
 * Method:    stringFromat
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_liujs_com_testndk_MainActivity_stringFromat
  (JNIEnv *ev, jobject obj){
    return (*ev)->NewStringUTF(ev,"好哈，我是刘劲松");
};

#ifdef __cplusplus
}
#endif
#endif
